version: "3"
services:
  configuration-service:
    container_name: configuration-service
    build:
      context: ./services/configuration-service
      dockerfile: Dockerfile
    image: configuration-service:0.0.7
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - policy-service
    environment:
      - policy.service.url=http://policy-service:8080

  policy-service:
    container_name: policy-service
    build:
      context: ./services/policy-service
      dockerfile: Dockerfile
    image: policy-service:0.0.4
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    privileged: true