version: "3"
services:
  configuration_service:
    container_name: configuration-service
    build:
      context: ./services/configuration-service
      dockerfile: Dockerfile
    hostname: localhost
    image: configuration-service:0.0.7
    ports:
      - "8080:8080"
    environment:
      - APP_SECURITY_ENABLED=false
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    privileged: true